services:
  web:
    build: .
    container_name: modules
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_ENV: docker
    depends_on:
      - db



  db:
    image: postgres:15
    container_name: modules_db
    environment:
      POSTGRES_DB: modules
      POSTGRES_USER: quantumd
      POSTGRES_PASSWORD: admlqq
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
